- errata_tool/connector.py
> Prepend exceptions with erratum ID if possible

- errata_tool/erratum.py
This is the start of ongoing work to refactor and split up the monster fetch function in Erratum. 
This will make it easier to subclass and extend functionality, as well as unittest behavior of the smaller worker functions.
> Erratum fetch refactor

- errata_tool/erratum.py
- errata_tool/security.py
quiet down addBuildsDirection() extra print
> General cleanup

- errata_tool/erratum.py
Change-Id: I568554486f6c872d6f4bc3fe965258a9e4bad67f
> Add flag for PST approval (security team)

- errata_tool/erratum.py
adapted from similar change made in shale
This adds checking distqa_tps results in Erratum._check_tps()
> Add needs_distqa flag checking

- README.rst
- errata_tool/connector.py
This system is deployed by SysOps and is intented for use with API clients.
> connector: note "official staging" server

- README.rst
Document how to set an advisory to "QE" state.
> README: give example of setState()

- errata_tool/connector.py
- errata_tool/erratum.py
> Centralize URL logic in to connector.py

- errata_tool/erratum.py
> erratum: Add missing 'request_sigs' flag

- errata_tool/erratum.py
> Clear signature flags if all builds have them

- errata_tool/erratum.py
ship target == published_date_override
> Add ship target to debug output

- README.rst
Give a general overview of this library and what it can do.
> README: improve library description

- errata_tool/erratum.py
> Fix checks on qe_group/qe_email

- .travis.yml
- errata_tool/connector.py
- errata_tool/erratum.py
- python-errata-tool.spec
- setup.py
This adds python-six as a dependency, but requests (via urllib3) already depends on that.
> fix some python 3 syntax issues and add ci

- errata_tool/products.py
> Fix some releases not having product links populated

- errata_tool/products.py
* get_release/get_version/get_product:
Added for finding each by name or ID; get_product
is for consistency.
* Add Bugzilla flags.
* Don't crash if importing bad data; simply do a proper
query instead.
> products: Minor feature additions

- errata_tool/erratum.py
> Fix traceback in dump() while debugging

- errata_tool/erratum.py
> Fix traceback for bad concatenation

- errata_tool/products.py
> Fix traceback if a release has no versions associated.

- errata_tool/erratum.py
> erratum: properly update text-only field

- errata_tool/connector.py
Resolves: https://github.com/red-hat-storage/errata-tool/issues/18
> disable mutal_auth

- errata_tool/erratum.py
> erratum: Add RHSA support

- errata_tool/erratum.py
I had a hard time immediately grasping what is going on in this
`_get_build_list()` method. Switch to more descriptive variable names so it's
easier to read.
> _get_build_list: better variable names for product versions and builds

- errata_tool/connector.py
- errata_tool/tests/conftest.py
- errata_tool/tests/test_release.py
- python-errata-tool.spec
- setup.py
Rewritten to user python-kerberos, which is kept up to date and py3.x compatible
> Extract user from krbV ticket

- README.rst
- errata_tool/release.py
- errata_tool/tests/fixtures/errata.devel.redhat.com/release/783/advisories.json
- errata_tool/tests/test_release.py
This method allows users to find all advisories for a given release.
> release: add advisories()

- README.rst
- bin/errata-tool
- errata_tool/cli/advisory.py
- errata_tool/cli/main.py
- errata_tool/cli/product.py
- errata_tool/cli/release.py
- errata_tool/tests/cli/test_advisory_cli.py
- errata_tool/tests/cli/test_main_cli.py
- errata_tool/tests/cli/test_product_cli.py
- errata_tool/tests/cli/test_release_cli.py
- python-errata-tool.spec
- setup.py
This installs a uility "errata-tool" in the user's $PATH.
> add basic errata-tool CLI

- README.rst
Erratum() constructor examples needed a few tweaks.
> README: fix constructor examples

- errata_tool/erratum.py
Note the ET BZ that tracks adding an officially-supported API for adding to the CC list.
> addCC: note the BZ for official API

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
- errata_tool/tests/test_release.py
- errata_tool/tests/test_rhsa_cve_list.py
Signed-off-by: Lon Hohberger <lon@metamorphism.com>
> erratum: Allow setting CVE names

- setup.py
Generate the source tarball and upload it to PyPI during `python setup.py release`
> setup.py: upload during "release" operation

- errata_tool/__init__.py
- errata_tool/erratum.py
- errata_tool/tests/fixtures/errata.devel.redhat.com/api/v1/user/3001931
- errata_tool/tests/test_advisory.py
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>
The pull request adds manager_id if manager_email does not exist.
> Fixes #136 Add support for manager_id

- errata_tool/erratum.py
Fixes flake8 error "E117 over-indented"
> erratum: fix over-indent

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
> Use publish_date as fallback if publish_date_override is not set

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
Add a unit test and docstring for the new `get_erratum_data()` method.
> erratum: add tests and docstring for get_erratum_data()

- errata_tool/connector.py
- added doctext to this method
- added support for 'raw' bool kwargs defaulting to False
- return the whole response object if raw set, otherwise
return json() results like normal
This is to allow usage of _get() for retreiving other content than API
where the returned content is always json object.
User of this option is responsible for handling error checking and decoding
> ErrataConnection: add raw kwargs to _get method

- errata_tool/erratum.py
- errata_tool/release.py
improve docstring consistency where already written
> Docstring cleanup

- .travis.yml
- README.rst
- setup.py
- tox.ini
Add tox.ini configuration
Reconfigure Travis CI to invoke tox instead of setuptools.
> run tests with tox

- errata_tool/cli/advisory.py
- errata_tool/tests/cli/test_advisory_cli.py
* Add `add-bugs` command to the `advisory` subcommand
* Add tests for the `add-bugs` command
Closes #240
> Add 'add-bugs' subcommand to 'advisory'
