red-hat-storage/errata-tool

- README.rst
- errata_tool/connector.py
- errata_tool/security.py
- errata_tool/tests/test_init.py
Prior to this change, the errata-tool lib disabled requests' SSL verification by default. (I assume this was done for the sake of ease-of-use, or maybe some non-prod host did not have a working cert.)
To improve security, enable SSL verification by default instead.
Add tests to ensure this behavior going forward.
Add documentation to the README for users to trust the root CA.
When SSL verification is enabled, requests prints a warning about a missing subjectAltName extension. Silence this warning (a server-side fix is in progress).
> verify HTTPS certificate by default

- errata_tool/erratum.py
Sync up recent changes
* `addBuilds()` handles non-RPMs
* add `setFileInfo()`
@lhh FYI
> addBuilds() support for non-RPMs

- .travis.yml
The "python setup.py test" command uses EasyInstall to install
dependencies, and the latest versions of urllib3 will fail to install
with EasyInstall:
error: Setup script exited with error in urllib3 setup command: Invalid
environment marker: python_version <= "2.7"
Use pip to install urllib3 instead.
> .travis.yml: fix urllib3 install during tests

- errata_tool/erratum.py
From Jarod Wilson <jarod@redhat.com>
The kernel team has need to query the kernel errata to check if the latest kernel build is under embargo. Discussion with folks on the errata-tools team revealed that this is conveyed by an erratum having the release_date field set, with a date that is in the future. This just adds a check for release_date, and compares it with the current date, copies the release_date field and sets an embargoed flag in Erratum, both of which can be consumed by scripts using this library.
> erratum: check if under embargo or not

- errata_tool/security.py
flake8 3.1.1 surfaces the following issue:
```
errata_tool/security.py:28:1: E305 expected 2 blank lines after class or
function definition, found 1
```
> flake8: fix recent error in security.py

- errata_tool/erratum.py
Guard was checking to make sure advisory was NEW_FILES before
it would attempt to change anything.  This appears to be a
legacy check that is no-longer needed.
Tested with:
publish_date_override changes in state == ON_QE
==> Update publish_date_override
update bugs while in state == ON_QE throws exception
==> errata_tool.exception.ErrataException: Erratum 26134: idsfixed: Errata Cannot remove non-security Bugs unless in NEW_FILES state
> drop the re-dundant and mis-leading guard in Erratum.update()

- errata_tool/erratum.py
Flag handling had a lot of duplicated logic -
if (flag not present):
add_flag
if (flag present):
remove_flag
This centralizes flag handling so consumers of errata-tool can use it, adds basic input validation (flags are all strings). Existing ABI/API compatibility is preserved.
> Add flag handler functions and centralize flag handling

- README.rst
- errata_tool/erratum.py
The ET supports setting the QE group during advisory creations and updates with the new `quality_responsibility_name` parameter.
https://bugzilla.redhat.com/1386089
Support this in our library as well.
> support setting QE group

- README.rst
The `url()` method returns the `/advisory/<id>` endpoint.
(The `/errata/<id>` is wrong, and in fact it's a 404 error server-side.)
> README: fix url() example output

- errata_tool/erratum.py
Take the status value from the JSON as-is. No need to decode the value.
This fixes an error on Python 3 where this decode() call would change
the value to a bytes type, which caused further errors in _fetch() when
trying to compare that bytes value with strings like 'QE'.
> erratum: do not decode errata status

- errata_tool/products.py
Not really an API so much as a data fetcher/aggregator
that tools can use to avoid hard-coding data normally
required to manipulate errata.
The caller is expected to cache data locally, since
this is a lot of calls and the data rarely changes.
Save/load callback functions can be specified when
instantiating, or the user can feed in the proper
data on their own.
The data is presently exposed primarly as large dicts.
> Add product, release, and version handling

- python-errata-tool.spec
Prior to this change, the RPM .spec would only build the python3 subpackage on Fedora.
Build both python2 and python3 subpackages on Fedora so that errata-tool can be integrated with other py2 libraries and scripts.
> rpm: always build python2 package

- README.rst
We cannot initialize Erratum with a simple int argument. ``__init__`` requires kwargs.
> README: fix Erratum initialization example

- README.rst
- errata_tool/erratum.py
- errata_tool/tests/conftest.py
- errata_tool/tests/test_change_docs_reviewer.py
Add a method to change an advisory's docs reviewer.
Refactor the GET mocking code to a proper pytest fixture with a call recorder. Also add `mock_post` fixture so we can mock APIs to which we must POST.
> add changeDocsReviewer()

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
Age is the number of days between creation and ship date,
or creation date and "today" if an erratum is not shipped.
This is useful for assembling historical data.
> Record filing date, ship date, and age

- errata_tool/products.py
- errata_tool/tests/test_products.py
1) Fetch all versions and releases for active products,
even disabled ones,
2) Assume users don't want inactive versions or releases,
but allow them to query them using disabled=True when
passed to get_versions() and get_releases()
3) Allow users to drop certain releases if they want,
4) Don't muck with async releases by default.
Product table version bumped since 'enabled' is now part
of version/release information.
> Product list functional changes

- README.rst
- errata_tool/erratum.py
- errata_tool/tests/test_add_cc.py
Use this to add someone to the CC list for an advisory.
This method is not documented in the ET's API docs - I just traced what the Javascript / HTML form was doing in Chrome.
> erratum: new addCC() method

- README.rst
Add another approach to using python-requests with RH's IT CA within a virtualenv.
> README: instructions for using the RH IT CA cert within Python

- errata_tool/erratum.py
Use single format strings, rather than concatenating a couple strings with multiple lines.
This makes the code more succinct and the URLs easier to read.
> simplify URL string constructions

- errata_tool/erratum.py
The REST API returns an advisory type values prefixed with "Pdc" or "pdc_*" in some cases.
This server behavior may change in the future (rhbz#1493773).
For now, handle this gracefully so we don't crash when creating new PDC-based advisories or loading existing ones.
> handle PDC advisory API responses

- MANIFEST.in
Archive created by "make dist" does not contain tests and LICENSE file.
This makes it impossible to build rpm package using provided spec file.
MANIFEST.in providing inclusion of tests and license into source distribution
was added.
> Include tests and license in source distribution

- errata_tool/erratum.py
- errata_tool/tests/test_add_builds.py
- errata_tool/tests/test_remove_builds.py
Expand coverage of unittests for erratum.py
addBuilds() and removeBuilds()
a couple of guard and edge case handling and more test cases to cover general good case scenarios
> Erratum unittests

- errata_tool/erratum.py
ET 3.16.1 no longer supports the `/advisory/<id>/rpmdiff_runs.json` API endpoint. Now it always returns an HTTP 500 error, which causes python-errata-tool's `_get()` to raise `LookupError`.
The Errata Tool team has decoupled rpmdiff from the ET, and there is an entirely separate web interface for that now.
> drop _check_rpmdiff

- README.rst
`setState()` only changes the internal representation of the state in the local Erratum class. It does not change the advisory state on the server.
We have to call `commit()` to send this change to the server.
> README: setState() requires commit()

- new-fixture.sh
This change allows new-fixture.sh to integrate more with the change from fec26a52e1c08434e6e27f9538f0c4d4476ca7a8, "tests: permit API fixtures as directories".
When downloading a new fixture file, if we already have a directory on disk for this test fixture, write to the corresponding .body file instead.
> new-fixture.sh: follow ".body" filename convention

- Makefile
Make it possible to generate SRPMs from .spec files that do not have "-1" as the release value.
The idea is to make it easier to package git snapshots.
> Makefile: RPM build improvements

- README.rst
```
README.rst:74: (ERROR/3) Unexpected indentation.
```
This should help with processing the README on pypi.org, see
https://pypi.org/project/errata-tool/
> README: fix rST indentation error

- README.rst
- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
This pull request adds `.missing_prod_listings`, a (possibly-empty) list of builds for which the Errata Tool could find no prod-listings.
This attribute helps users to know if they should reload the build list (as in the README), or possibly open a ticket with RCM.
> Erratum: add missing_prod_listings attribute

- errata_tool/connector.py
If we get an HTTP 500 response from the Errata Tool, we probably have a useful error message in the HTTP body.
As one example: when I try to create a new advisory for a new release before RCM has created the new release, the ET returns an HTTP 500 with the following JSON:
```json
{"error": "ERROR: Couldn't find Release without an ID"}
```
Instead of printing the json to STDOUT, return the data in the exception itself.
This allows callers to discover the specific error message. Callers can print human-readable explanations about what went wrong and what steps to take next (for example, "file an RCM ticket to create this new release").
> connector: raise with specific HTTP 500 error message

- Makefile
Use --dist-dir to write the tarball directly to the root of the tree, rather than moving it in a separate step.
Props to Lukas Holecek <lholecek@redhat.com> for this tip.
> make: simplify "dist" target

- README.rst
Give an example of attaching a container build with the `file_types` kwarg.
> README: document adding container builds

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
Adding a erratum.batch_id property, this will give the user the batch_id
number if the advisory is part of one.
Signed-off-by: Jason Joyce <fuzzball81@gmail.com>
> Adding basic batch_id information to erratum

- doc/conf.py
readthedocs.org does not support installing C-based libraries, so we cannot `import errata_tool` unless we mock these libraries in that environment.
MagicMock is in stdlib as of Python 3.3, so we require Python 3.3 in the readthedocs.org build environment.
> doc: mock C-based libraries on rtd.org

- python-errata-tool.spec
`python_version` is not available on Rawhide (Fedora 29). Use `python2_version` instead.
> rpm: change obsolete python_version macro to python2_version

- README.rst
- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
Support reading or setting the CPE text for text-only advisories.
> erratum: add .text_only_cpe attribute

- errata_tool/cli/advisory.py
- errata_tool/cli/build.py
- errata_tool/cli/main.py
- errata_tool/cli/product.py
- errata_tool/cli/release.py
When we call `add_subparsers()` on Python 2, Argparse will always require that sub-command.
On Python 3, Argparse's does not require the sub-command unless we tell it to do so. This would lead to a crash later on when we called `args.func()` because that attribute was not set.
> cli: require subparsers in python 3

- README.rst
Give an example of changing an advisory's type to "RHBA".
> README: add example of changing errata_type

- errata_tool/connector.py
Latest versions of flake8 warn about the "\." here because it was not in a raw string.
It looks like this is a Python 3.7 deprecation thing.
> connector: use raw string for "\."

- setup.py
This was a leftover from the initial import to GitHub. As it turned out, we never used httpretty for testing.
> setup.py: rm unused test dependency

- errata_tool/connector.py
Prior to this change, if we GET a URL and received a HTTP 500 response, we would raise a simple LookupError with no further information about what went wrong.
Update the error handling logic in `_get()` so that we will raise `ErrataException` instead. This will give us a lot more information about the URL we were trying to access and the response back from the server.
> connector: better debugging for HTTP 500 GET errors

- errata_tool/erratum.py
`push()` returns a list, not a dict, and the `push_id` value is really just `id`. Update the `push()` docstring to for these changes.
> erratum: fix docs for push() return type

- setup.py
The latest versions of pytest (v4.1) require a list of strings here, not one single string.
> setup.py: split args to pytest.main

- errata_tool/user.py
The Errata Tool does not return a "name" value in the user REST API.
It's "login_name" instead.
> user: use login_name for __str__

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
This bug tracks adding the manager email address to the Errata Tool REST API: https://bugzilla.redhat.com/show_bug.cgi?id=1664884
Link to it in the comments where we would have assigned `.manager_email`.
> erratum: update comments about missing manager

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
Prior to this change, when querying an existing advisory, the `.package_owner_email` was actually set to the advisory's "reporter" value.
In an Errata Tool advisory, a Package Owner and a Reporter can be two different people.
Assign the `.package_owner_email` attribute to the `package_owner` value we get back from the Errata Tool's JSON.
Expose the advisory's "reporter" field in a new `.reporter` attribute.
> erratum: fix .package_owner_email assignment and add .reporter attribute

- README.rst
Since we've dropped PDC support, remove this final reference from the README.
> README: rm additional PDC reference

- errata_tool/cli/release.py
- for errata-tool release list-advisories --status OPEN <release_name>
- 'OPEN' == ['NEW_FILES', 'QE', 'REL_PREP', 'IN_PUSH']
This attempts to make it easier to use the errata-tool cli for listing advisories for a release.
> add errata-tool cli release status OPEN mapping

- errata_tool/erratum.py
We recently hit an NPE with `errata_tool.Erratum()`, which breaks a lot of our automation using this library. We found some shipped advisories has `actual_ship_date` set to `null` but errata_tool always tries to format that field to string. This PR just adds a simple NPE check.
For example, https://errata.devel.redhat.com/api/v1/erratum/43686:
```
advisory = errata_tool.Erratum(errata_id=43686)
File "/home/dev/.local/lib/python2.7/site-packages/errata_tool/erratum.py", line 131, in __init__
self._fetch(kwargs['errata_id'])
File "/home/dev/.local/lib/python2.7/site-packages/errata_tool/erratum.py", line 235, in _fetch
d = time.strptime(str(d), '%Y-%m-%dT%H:%M:%SZ')
File "/usr/lib64/python2.7/_strptime.py", line 478, in _strptime_time
return _strptime(data_string, format)[0]
File …
```
> NPE when `actual_ship_date` is None

- errata_tool/tests/test_add_builds.py
pytest deprecated the message parameter
the replacement is to use match
Resolves: https://github.com/red-hat-storage/errata-tool/issues/163
> pytest deprected warning about message

- errata_tool/tests/test_release.py
Prior to this change, pytest was not invoking the blocker_flags() method
because it did not start with "test\_". Rename the method so that pytest
invokes it.
Our "expected" values were ordered incorrectly when compared to our test
fixture data. Re-order the expected flags so that "pm_ack" is the final
one.
With these changes, pytest properly exercises .blocker_flags attribute.
> tests: fix release.blocker_flags test

- errata_tool/build.py
- errata_tool/tests/test_build.py
- reworked _fetch to extract all_errataum_ids and released_errata_id
- reworked _fetch to not create erratum objects
- only load/create erratum objects when asked for
- added all_erratum_ids and released_errata_id properties
Performance improvement of build search object, only load/populate Erratum when you need them.  Allowing property accessors to the list of errata_id's without the time penalty of populating full Erratum objects.
Resolves: https://github.com/red-hat-storage/errata-tool/issues/179
> build: lazy-load erratum when asked for

- python-errata-tool.spec
We cannot build Python 2 on Fedora 31+ any more because that distro does not have all the py2 dependencies.
Build Python 2 on el7 only. For everything else (Fedora and RHEL 8+), build Python 3-only.
> rpm: py3-only for Fedora and EPEL 8+

- errata_tool/cli/main.py
Prior to this change, every time we added a new sub-command, we had to list the sub-command twice in main.py.
Use pkgutil.iter_modules and importlib.import_module to import all the sub-command modules dynamically. This reduces the copy-and-paste boilerplate and makes it easier to scale this tool to more sub-commands.
> cli: auto-load all subcommand libraries

- errata_tool/erratum.py
While working with @sosiouxme (cc: @thiagoalessio) on an [Elliott issue](https://github.com/openshift/elliott/pull/172) we found that errata_tool returned a server error when there's an attempt to update an existing advisory's security impact, i.e. 
`advisory.update(security_impact=<val>)`
It turned out that security_impact field is only set in case of **new** RHSA advisories, so the fix was simply moving the block outside of new block. 
This is my first time contributing to ET, so I'm not aware of what exactly I need to do to get this fixed (or if it is even an issue..). I can write a unit test or two if that's recommended. @ktdreyer @yazug Please advice, thank you.
> Update security impact field for an existing RHSA advisory

- python-errata-tool.spec
rpmlint and modern RPM versions warn about the comments after the `%endif` directives.
```
python-errata-tool.spec: E: specfile-error warning: extra tokens at the end of %endif directive in line 58:  %endif # with_python3
```
The conditionals are so small that it's fairly easy to read what the code is doing. Remove the comments to silence this error message.
> rpm: remove comments after %endif directives

- errata_tool/erratum.py
Prior to this commit, users could not update owner and manager email addresses for existing advisories. We sent the parameters when creating a new advisory, but not when editing an existing advisory.
Move the pdata assignments out of the `if self._new` conditional so that we send these parameters during advisory creations and updates.
Fixes: #208
> erratum: fix updating owner and manager emails

- errata_tool/tests/test_release.py
EPEL 7 has pytest v2.7.0, and `len(recwarn)` only works in pytest 2.8.0+. Use the older `recwarn.list` syntax so that the test suite passes in an EPEL 7 chroot.
> tests: use recwarn.list for EPEL 7's pytest 2.7.0

- README.rst
- doc/conf.py
- doc/index.rst
- errata_tool/connector.py
- errata_tool/erratum.py
- errata_tool/tests/conftest.py
- errata_tool/tests/test_release.py
- python-errata-tool.spec
- setup.py
Remove the username discovery in connector.py. The `self._username` property is not easy to support with the switch from python-kerberos to python-gssapi.
requests-kerberos is not well-maintained upstream and Fedora is dropping it entirely. requests-gssapi is an up-to-date replacement.
Fixes: #135
> revert _username handling and replace requests-kerberos with requests-gssapi

- errata_tool/cli/dump-config.py
- python-errata-tool.spec
- setup.py
This change adds a frontend for dumping many of the most relevant
data fields in a product's ET configuration which allows for easy
introspection as well as provides an easy migration path to porting
to ansible configurations.
Signed-off-by: Joshua Stone <jostone@redhat.com>
> Add a dump-config CLI subcommand

- Makefile
In Fedora 31+, `python` means `python3`. https://fedoraproject.org/wiki/Changes/Python_means_Python3
On these platforms, we need to use the `print()` function in order to properly assign the `VERSION` variable.
> make: VERSION assignment on py3

- errata_tool/cli/dump-config.py
The dump-config functionality in errata-tool does not check for
duplicate CDN repos, which can occur with repos that are part of
multiple variants. This change adds a check to avoid duplicates in
dump-config output.
> Avoid populating CDN repo entries in dump-config with duplicates

- Makefile
rpkg's `--dist` argument is old and does not work any more. Use `--release` instead.
> make: use --release arg to fedpkg

- errata_tool/erratum.py
- errata_tool/product_version.py
- errata_tool/release.py
- errata_tool/tests/conftest.py
- errata_tool/tests/test_product_version.py
- errata_tool/tests/test_variant.py
- errata_tool/variant.py
Noticed that when updating an advisory, we
were missing to include jira_issues in "idsfixed"
This was causing jira issues to be removed
from an advisory.
https://errata.devel.redhat.com/developer-guide/api-http-api.html#api-post-apiv1erratum
> Include jira issues when updating advisory

- errata_tool/erratum.py
- errata_tool/tests/test_advisory.py
jira issues items are in  type of `string` while in bugzilla the bug value is type of `int`, they can't be used together in `sorted` and will raise error like
```
TypeError: '<' not supported between instances of 'str' and 'int'
```
instead, use `set` to compare two lists
> fix value type issue

- errata_tool/product_version.py
- errata_tool/tests/test_product_version.py
Errata Tool added use_quay_for_containers which some products are starting to use but may introduce regressions, which in turn may not be obvious based on the current product configuration dump. This change adds that property to the render output.
> Add use_quay_for_containers to ProductVersion render output

- README.rst
- errata_tool/cli/advisory.py
- errata_tool/tests/cli/test_advisory_cli.py
The enhancement was made in response to : https://issues.redhat.com/browse/SPMM-9887
Errata tool has a feature of blocking advisories. However, the blockers block pushing of dependent advisories which are blocked by an advisory which is not in PUSH_READY state.
Ansible automation platform requires to block operator pushes until the container images they operate on to be in SHIPPED_LIVE state.
> Wait and push advisories based on state

- .github/workflows/tests.yml
Instead of running tox with `tox -e py`, run with eg. `tox -e py27`. This matches more closely what a local user would do, and it allows us to filter dependencies in `tox.ini` according to Python versions.
> github: run tox tests with pyXX environments

- README.rst
Document the `.errata_bugs` property in the README.
> README: document how to read the current list of bugs

- errata_tool/tests/cli/test_advisory_cli.py
pytest 2.7 does not use a namedtuple for `capsys.readouterr()`.
> tests: pytest 2.7 / py27 compatibility

- .github/workflows/tests.yml
GitHub no longer supports running Python 2.7 natively.
> github: test py2 on el7

- errata_tool/release.py
Prior to this change, if a user created a `Release` class by specifying an ID number instead of a `name` string, the class would always set the `name` property to `None`. For example, this would be `None`:
```python
Release(id=1234).name
```
Assign `name` when we process all the other data attributes in `_setattr()`.
> release: always assign `name` from server data

- errata_tool/product_version.py
- errata_tool/tests/test_product_version.py
This reverts commit d5e3fa2c746634ed32ccf7abaea8e239362f5914.
`use_quay_for_containers` does not appear to be used anymore in the Errata Tool API so we should remove it.
> Revert "Add use_quay_for_containers to ProductVersion render output"

- errata_tool/connector.py
Handle the case where the page number is the first API parameter. With an API like '/v1/API/releases' the URL should be '/v1/API/releases?page[number]=1', not '/v1/API/releases&page[number]=1'. Handle this correctly.
> Handle the page number as the first API parameter.
